import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FloatingDock } from "@/components/dock";
import {
  IconCategory,
  IconFileDescription,
  IconHome,
  IconUser,
} from "@tabler/icons-react";
import NextUIProvider from "@/lib/providers";
import Header from "@/components/header";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextUIProvider>
          <Header />
          <div className="flex flex-col justify-center items-center mt-[16px] mx-[16px] md:mx-0">
            <div className="grid grid-cols-2 md:grid-cols-6 w-full min-h-screen max-w-[1024px]">
              <main className="col-span-6">{children}</main>
            </div>
            <FloatingDock
              items={[
                { href: "/", title: "Home", icon: <IconHome /> },
                {
                  href: "/recipes",
                  title: "Recipes",
                  icon: <IconFileDescription />,
                },
                {
                  href: "/categories",
                  title: "Categories",
                  icon: <IconCategory />,
                },
                { href: "/profile", title: "Profile", icon: <IconUser /> },
              ]}
            />
          </div>
        </NextUIProvider>
      </body>
    </html>
  );
}
